from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QFont, QIcon, QPixmap


class Ui_Lesson(object):
    def setupUi(self, Lesson):
        Lesson.setObjectName("Lesson")
        Lesson.resize(1111, 962)
        self.centralwidget = QtWidgets.QWidget(parent=Lesson)
        self.centralwidget.setObjectName("centralwidget")
        self.heading_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.heading_label.setGeometry(QtCore.QRect(0, 0, 1111, 81))
        self.heading_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.heading_label.setObjectName("heading_label")
        self.main_text = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.main_text.setGeometry(QtCore.QRect(250, 120, 600, 625))
        self.main_text.setObjectName("main_text")
        self.first_photo = QtWidgets.QLabel(parent=self.centralwidget)
        self.first_photo.setGeometry(QtCore.QRect(20, 175, 201, 201))
        self.first_photo.setObjectName("first_photo")
        self.second_photo = QtWidgets.QLabel(parent=self.centralwidget)
        self.second_photo.setGeometry(QtCore.QRect(20, 510, 201, 201))
        self.second_photo.setObjectName("second_photo")
        self.third_photo = QtWidgets.QLabel(parent=self.centralwidget)
        self.third_photo.setGeometry(QtCore.QRect(880, 505, 201, 201))
        self.third_photo.setObjectName("third_photo")
        self.fourth_photo = QtWidgets.QLabel(parent=self.centralwidget)
        self.fourth_photo.setGeometry(QtCore.QRect(880, 170, 201, 201))
        self.fourth_photo.setObjectName("fourth_photo")
        self.first_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.first_label.setGeometry(QtCore.QRect(60, 390, 191, 21))
        self.first_label.setObjectName("first_label")
        self.second_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.second_label.setGeometry(QtCore.QRect(60, 730, 191, 21))
        self.second_label.setObjectName("second_label")
        self.fourth_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.fourth_label.setGeometry(QtCore.QRect(915, 380, 191, 21))
        self.fourth_label.setObjectName("fourth_label")
        self.third_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.third_label.setGeometry(QtCore.QRect(915, 720, 191, 21))
        self.third_label.setObjectName("third_label")
        self.next_lesson_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.next_lesson_button.setGeometry(QtCore.QRect(650, 830, 151, 41))
        self.next_lesson_button.setObjectName("next_lesson_button")
        self.return_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.return_button.setGeometry(QtCore.QRect(480, 830, 151, 41))
        self.return_button.setObjectName("return_button")
        self.previous_lesson_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.previous_lesson_button.setGeometry(QtCore.QRect(310, 830, 151, 41))
        self.previous_lesson_button.setObjectName("previous_lesson_button")
        Lesson.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Lesson)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 26))
        self.menubar.setObjectName("menubar")
        Lesson.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Lesson)
        self.statusbar.setObjectName("statusbar")
        Lesson.setStatusBar(self.statusbar)

        self.big_font = QFont('Rockwell Extra Bold', 16)
        self.small_font = QFont('Rockwell Extra Bold', 7)
        self.avg_font = QFont('Rockwell Extra Bold', 8)

        self.big_font.setBold(True)
        self.small_font.setBold(True)
        self.avg_font.setBold(True)

        self.heading_label.setFont(self.big_font)
        self.third_label.setFont(self.small_font)
        self.fourth_label.setFont(self.small_font)
        self.first_label.setFont(self.small_font)
        self.second_label.setFont(self.small_font)
        self.return_button.setFont(self.avg_font)
        self.next_lesson_button.setFont(self.avg_font)
        self.previous_lesson_button.setFont(self.avg_font)

        self.retranslateUi(Lesson)
        QtCore.QMetaObject.connectSlotsByName(Lesson)

    def retranslateUi(self, Lesson):
        _translate = QtCore.QCoreApplication.translate
        Lesson.setWindowTitle(_translate("Lesson", "Lesson"))
        self.heading_label.setText(_translate("Lesson", "Тема"))
        self.main_text.setHtml(_translate("Lesson", "Текст"))
        self.first_photo.setText(_translate("Lesson", ""))
        self.second_photo.setText(_translate("Lesson", ""))
        self.third_photo.setText(_translate("Lesson", ""))
        self.fourth_photo.setText(_translate("Lesson", ""))
        self.first_label.setText(_translate("Lesson", ""))
        self.second_label.setText(_translate("Lesson", ""))
        self.fourth_label.setText(_translate("Lesson", ""))
        self.third_label.setText(_translate("Lesson", ""))
        self.next_lesson_button.setText(_translate("Lesson", "Следующий урок"))
        self.return_button.setText(_translate("Lesson", "Назад"))
        self.previous_lesson_button.setText(_translate("Lesson", "Прошлый урок"))
