from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QuizIntroduction(object):
    def setupUi(self, QuizIntroduction):
        QuizIntroduction.setObjectName("QuizIntroduction")
        QuizIntroduction.resize(845, 748)
        font = QtGui.QFont()
        font.setPointSize(8)
        QuizIntroduction.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=QuizIntroduction)
        self.centralwidget.setObjectName("centralwidget")
        self.heading_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.heading_label.setGeometry(QtCore.QRect(0, 0, 831, 91))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.heading_label.setFont(font)
        self.heading_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.heading_label.setObjectName("heading_label")
        self.level_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.level_label.setGeometry(QtCore.QRect(140, 180, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.level_label.setFont(font)
        self.level_label.setObjectName("level_label")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(530, 190, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.questions_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.questions_label.setGeometry(QtCore.QRect(140, 300, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.questions_label.setFont(font)
        self.questions_label.setObjectName("questions_label")
        self.spinBox = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(530, 310, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Fluent Icons")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.next_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(350, 460, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.next_button.setFont(font)
        self.next_button.setObjectName("next_button")
        self.return_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.return_button.setGeometry(QtCore.QRect(350, 500, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.return_button.setFont(font)
        self.return_button.setObjectName("return_button")
        QuizIntroduction.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=QuizIntroduction)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 23))
        self.menubar.setObjectName("menubar")
        QuizIntroduction.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=QuizIntroduction)
        self.statusbar.setObjectName("statusbar")
        QuizIntroduction.setStatusBar(self.statusbar)

        self.retranslateUi(QuizIntroduction)
        QtCore.QMetaObject.connectSlotsByName(QuizIntroduction)

    def retranslateUi(self, QuizIntroduction):
        _translate = QtCore.QCoreApplication.translate
        QuizIntroduction.setWindowTitle(_translate("QuizIntroduction", "QuizIntroduction"))
        self.heading_label.setText(_translate("QuizIntroduction", "Перед началом викторины:"))
        self.level_label.setText(_translate("QuizIntroduction", " 1. Укажите уровень "))
        self.comboBox.setItemText(0, _translate("QuizIntroduction", "Новичок"))
        self.comboBox.setItemText(1, _translate("QuizIntroduction", "Любитель"))
        self.comboBox.setItemText(2, _translate("QuizIntroduction", "Эксперт"))
        self.questions_label.setText(_translate("QuizIntroduction", " 2. Укажите количество вопросов"))
        self.next_button.setText(_translate("QuizIntroduction", "Дальше"))
        self.return_button.setText(_translate("QuizIntroduction", "Назад"))
