from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QFont, QIcon


class Ui_UsefulMaterial(object):
    def setupUi(self, UsefulMaterial):
        UsefulMaterial.setObjectName("UsefulMaterial")
        UsefulMaterial.resize(983, 788)
        UsefulMaterial.setMaximumSize(QtCore.QSize(983, 16777215))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        UsefulMaterial.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=UsefulMaterial)
        self.centralwidget.setObjectName("centralwidget")
        self.heading_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.heading_label.setGeometry(QtCore.QRect(0, 0, 981, 71))
        self.heading_label.setMaximumSize(QtCore.QSize(981, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.heading_label.setFont(font)
        self.heading_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.heading_label.setObjectName("heading_label")
        self.first_article = QtWidgets.QPushButton(parent=self.centralwidget)
        self.first_article.setGeometry(QtCore.QRect(0, 140, 981, 71))
        self.first_article.setMaximumSize(QtCore.QSize(981, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.first_article.setFont(font)
        self.first_article.setObjectName("first_article")
        self.second_article = QtWidgets.QPushButton(parent=self.centralwidget)
        self.second_article.setGeometry(QtCore.QRect(0, 220, 981, 71))
        self.second_article.setMaximumSize(QtCore.QSize(981, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.second_article.setFont(font)
        self.second_article.setObjectName("second_article")
        self.third_article = QtWidgets.QPushButton(parent=self.centralwidget)
        self.third_article.setGeometry(QtCore.QRect(0, 300, 981, 71))
        self.third_article.setMaximumSize(QtCore.QSize(981, 71))
        self.third_article.setObjectName("third_article")
        self.fourth_article = QtWidgets.QPushButton(parent=self.centralwidget)
        self.fourth_article.setGeometry(QtCore.QRect(0, 380, 981, 71))
        self.fourth_article.setMaximumSize(QtCore.QSize(981, 71))
        self.fourth_article.setObjectName("fourth_article")
        self.fifth_article = QtWidgets.QPushButton(parent=self.centralwidget)
        self.fifth_article.setGeometry(QtCore.QRect(0, 460, 981, 71))
        self.fifth_article.setMaximumSize(QtCore.QSize(981, 71))
        self.fifth_article.setObjectName("fifth_article")
        self.sixth_article = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sixth_article.setGeometry(QtCore.QRect(0, 540, 981, 71))
        self.sixth_article.setMaximumSize(QtCore.QSize(981, 71))
        self.sixth_article.setObjectName("sixth_article")
        self.return_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.return_button.setGeometry(QtCore.QRect(400, 690, 191, 41))
        self.return_button.setMaximumSize(QtCore.QSize(191, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.return_button.setFont(font)
        self.return_button.setObjectName("return_button")
        UsefulMaterial.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=UsefulMaterial)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 983, 26))
        self.menubar.setObjectName("menubar")
        UsefulMaterial.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=UsefulMaterial)
        self.statusbar.setObjectName("statusbar")
        UsefulMaterial.setStatusBar(self.statusbar)

        self.big_font = QFont('Rockwell Extra Bold', 16)
        self.average_font = QFont('Rockwell Extra Bold', 10)
        self.small_font = QFont('Rockwell Extra Bold', 9)

        self.big_font.setBold(True)
        self.average_font.setBold(True)
        self.small_font.setBold(True)

        self.heading_label.setFont(self.big_font)
        self.first_article.setFont(self.average_font)
        self.second_article.setFont(self.average_font)
        self.third_article.setFont(self.average_font)
        self.fourth_article.setFont(self.average_font)
        self.fifth_article.setFont(self.average_font)
        self.sixth_article.setFont(self.average_font)
        self.return_button.setFont(self.small_font)

        self.widgets = [self.heading_label, self.first_article, self.second_article,
                        self.third_article, self.fourth_article, self.fifth_article,
                        self.sixth_article, self.return_button]
        
        self.return_button.setIcon(QIcon('data/icons/return.svg'))

        self.retranslateUi(UsefulMaterial)
        QtCore.QMetaObject.connectSlotsByName(UsefulMaterial)

    def retranslateUi(self, UsefulMaterial):
        _translate = QtCore.QCoreApplication.translate
        UsefulMaterial.setWindowTitle(_translate("UsefulMaterial", "UsefulMaterial"))
        self.heading_label.setText(_translate("UsefulMaterial", "Полезные материалы"))
        self.first_article.setText(_translate("UsefulMaterial", "Статья 1. Древний Египет: культура и быт"))
        self.second_article.setText(_translate("UsefulMaterial", "Статья 2. Феодализм в средневековой Европе"))
        self.third_article.setText(_translate("UsefulMaterial", "Статья 3. Леонардо Да Винчи: жизнь и достижения"))
        self.fourth_article.setText(_translate("UsefulMaterial", "Статья 4. Американская революция: причины и последствия"))
        self.fifth_article.setText(_translate("UsefulMaterial", "Статья 5. Холодная война: конфликт идеологий"))
        self.sixth_article.setText(_translate("UsefulMaterial", "Статья 6. Глобализация: влияние на современное общество"))
        self.return_button.setText(_translate("UsefulMaterial", "Назад"))
